#!/bin/bash

pip --version > /dev/null || {
  echo "pip not installed. Installing..."
  sudo easy_install pip
}

virtualenv --version > /dev/null || {
  echo "virtualenv not installed. Installing..."
  sudo pip install virtualenv
}

gaenv -h > /dev/null || {
  echo "gaenv not installed. Installing..."
  sudo pip install gaenv
}

virtualenv env
source env/bin/activate
pip install -r requirements.txt
gaenv --lib lib --no-import
deactivate
